### ISSUE TITLE
Withdrawal and Deposit buttons should open the "New With./Dep." page

### ISSUE THREAD

**Issue by tloltman** [tloltman/Qbill-ionic#15]
There's only a single Ionic "page" for both the New Withdrawal and New Deposit Page. We will use the Ionic navPush along with a parameter (just a string) which specifies if the page should represent a new withdrawal or deposit.

We don't need to add any functionality to the withdrawal/deposit page besides maybe having the cancel button close (pop) the page when it's clicked. Just make the two buttons on the "home" page push the withdrawal/deposit pages with the correct parameter so that the title shows "New Withdrawal" or "New Deposit" accordingly.

**Comment by tloltman** [comment]
So when working on an issue this is a good way to do it I think:

- create a new branch for the issue from the develop branch
- name the branch using a short project id (we'll use QB for Quibill) followed by the issue number      followed by some short description of what the branch is for
- checkout this new branch locally and make all the changes/fixes
- commit and push your changes to the github remote branch
- create a pull request from the new issue branch back into the develop branch

Example - for this issue you could create a new branch from develop and name it:
QB-15-buttons-on-home-page-should-open-new-transaction-pages

**Comment by whimstack** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Withdrawal and Deposit buttons should open the "New With./Dep." page #15](https://trello.com/c/aFUOdAVG/14-withdrawal-and-deposit-buttons-should-open-the-new-with-dep-page-15)

**Comment by tloltman** [comment]
I merged your changes with the develop branch!
