### ISSUE TITLE
Add transactions page

### ISSUE THREAD

**Issue by tloltman** [tloltman/Qbill-ionic#25]
Should be based on the image, I added the actual page files to the develop branch, but the content needs to be added. The page also should be opened when the "View All Transaction" button is pressed on the home page.

The "All Withdrawal Deposit" tabs should be clickable, but they don't need to do anything yet.
The <ion-segment seems like the perfect candidate for this.

![quibill-transactions](https://cloud.githubusercontent.com/assets/21272875/20851996/23b9c7a2-b8a9-11e6-811b-d3787e321ecc.png)

**Comment by whimstack** [comment]
Finished the basic page construction. Still need to add styling and functionality. These should be new issues.
